# Tasks for Each Focus Group Agent

tech_enthusiast_task:
  description: >
    Review {topic} with a focus on technological aspects, innovation, and relevance to current tech trends.
    Video Context: {video_context}
    Audio Context: {audio_context}
    Text Context: {text_context}
    Agency Info: {agency_info}
  expected_output: >
    A list with 5-7 bullet points highlighting the tech-related strengths, weaknesses, and standout features of these.
    And also a rating 1 out of 10 regarding how likely it should be used by the agency.
  agent: tech_enthusiast

young_social_media_influencer_task:
  description: >
    Assess {topic} from a social media perspective, focusing on shareability, visual appeal, and engagement potential for young audiences.
    Video Context: {video_context}
    Audio Context: {audio_context}
    Text Context: {text_context}
    Agency Info: {agency_info}
  expected_output: >
    A list with 5-7 bullet points evaluating how appealing these are for social media platforms and younger audiences.
    And also a rating 1 out of 10 regarding how likely it should be used by the agency.
  agent: young_social_media_influencer

business_professional_task:
  description: >
    Analyze {topic} with a focus on business applications, potential ROI, and alignment with professional goals.
    Video Context: {video_context}
    Audio Context: {audio_context}
    Text Context: {text_context}
    Agency Info: {agency_info}
  expected_output: >
    A list with 5-7 bullet points summarizing the value and implications of these for business professionals.
    And also a rating 1 out of 10 regarding how likely it should be used by the agency.
  agent: business_professional

family_focus_viewer_task:
  description: >
    Evaluate {topic} from a family-oriented perspective, focusing on inclusivity, appeal to family members, and age appropriateness.
    Video Context: {video_context}
    Audio Context: {audio_context}
    Text Context: {text_context}
    Agency Info: {agency_info}
  expected_output: >
    A list with 5-7 bullet points detailing how these might resonate with family audiences.
    And also a rating 1 out of 10 regarding how likely it should be used by the agency.
  agent: family_focus_viewer

environmentalist_task:
  description: >
    Conduct an assessment of {topic} with respect to sustainability, environmental friendliness, and eco-consciousness.
    Video Context: {video_context}
    Audio Context: {audio_context}
    Text Context: {text_context}
    Agency Info: {agency_info}
  expected_output: >
    A list with 5-7 bullet points evaluating on these environmental impact and sustainability.
    And also a rating 1 out of 10 regarding how likely it should be used by the agency.
  agent: environmentalist

senior_expert_task:
  description: >
    Analyze {topic} for senior accessibility, clarity, and practical relevance to older demographics.
    Video Context: {video_context}
    Audio Context: {audio_context}
    Text Context: {text_context}
    Agency Info: {agency_info}
  expected_output: >
    A list with 5-7 bullet points on how accessible and relevant {topic} is for senior audiences.
    And also a rating 1 out of 10 regarding how likely it should be used by the agency.
  agent: senior_expert

# Task for Reporting Analyst

reporting_task:
  description: >
    Synthesize the insights from all agents into a comprehensive report, highlighting main points from each focus group perspective.
    Average the ratings from each agent to provide an overall recommendation for each context.
    Ensure the report captures key insights, contrasting opinions, and provides actionable recommendations where appropriate.
    Video Context: {video_context}
    Audio Context: {audio_context}
    Text Context: {text_context}
    Agency Info: {agency_info}
  expected_output: >
    A detailed report with sections summarizing each agent's perspective, formatted as markdown.
  agent: reporting_analyst